// <auto-generated />
using System;
using Adm_Agenda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adm_Agenda.Migrations
{
    [DbContext(typeof(Context_db))]
    [Migration("20221121105203_Gerando base de dados Agenda")]
    partial class GerandobasededadosAgenda
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Adm_Agenda.Models.mdAgenda", b =>
                {
                    b.Property<int>("IdAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("dtCompromisso")
                        .HasColumnType("date");

                    b.Property<int>("idContato")
                        .HasColumnType("int");

                    b.Property<int>("idTipo")
                        .HasColumnType("int");

                    b.HasKey("IdAgenda");

                    b.ToTable("tb_Agenda");
                });

            modelBuilder.Entity("Adm_Agenda.Models.mdContatos", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdEndereco")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("IdContato");

                    b.ToTable("tbContatos");
                });

            modelBuilder.Entity("Adm_Agenda.Models.mdEndereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Ibge")
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.HasKey("IdEndereco");

                    b.ToTable("tb_Endereco");
                });

            modelBuilder.Entity("Adm_Agenda.Models.mdTipoCompromisso", b =>
                {
                    b.Property<int>("IdTipoCompromisso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoTipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTipoCompromisso");

                    b.ToTable("tb_TipoCompromisso");
                });
#pragma warning restore 612, 618
        }
    }
}
